# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YL-YvsvUuRsK7RA6EzDyEj1bETfrzBvB
"""

!pip install -q earthengine-api geemap

import ee
import geemap

ee.Authenticate()
ee.Initialize(project='whee-486607')

# Punjab–Haryana wheat belt (manageable size)
region = ee.Geometry.Rectangle([74, 29, 77, 31])



"""# NEW BEGINNING"""

# Wheat belt region (Punjab + Haryana)
region = ee.Geometry.Rectangle([
    74.5, 29.0,   # bottom-left (lon, lat)
    76.8, 31.5    # top-right (lon, lat)
])

# Wheat season (Rabi)
start = "2022-11-01"
end   = "2023-04-30"

s2 = (
    ee.ImageCollection("COPERNICUS/S2_SR")
    .filterBounds(region)
    .filterDate(start, end)
)

ndvi = s2.map(
    lambda img: img.normalizedDifference(["B8", "B4"]).rename("NDVI")
)

ndvi_max = ndvi.max()

# Wheat detection rule (proven)
wheat_mask = ndvi_max.gt(0.35).rename("WHEAT")

task = ee.batch.Export.image.toDrive(
    image=wheat_mask,
    description="India_Wheat_Map_FINAL",
    folder="GEE_Wheat",
    fileNamePrefix="wheat_map",
    region=region,
    scale=10,        # Sentinel-2 native resolution
    maxPixels=1e13
)

task.start()
print("Export started")

from google.colab import drive
drive.mount('/content/drive')

import rasterio
import numpy as np

path = "/content/drive/MyDrive/GEE_Wheat/wheat_map.tif"

with rasterio.open(path) as src:
    data = src.read(1)
    print("Shape:", data.shape)
    print("Unique values:", np.unique(data))

# Sentinel-2 NDVI time series (no masking, proven safe)
s2_ts = (
    ee.ImageCollection("COPERNICUS/S2_SR")
    .filterBounds(region)
    .filterDate("2022-11-01", "2023-04-30")
)

ndvi_ts = s2_ts.map(
    lambda img: img.normalizedDifference(["B8", "B4"])
                  .rename("NDVI")
                  .updateMask(wheat_mask)   # IMPORTANT
                  .set("system:time_start", img.get("system:time_start"))
)

def weekly_composite(start_date, weeks, collection):
    def make_week(w):
        start = ee.Date(start_date).advance(w, "week")
        end   = start.advance(1, "week")
        img = collection.filterDate(start, end).mean()
        return img.set("system:time_start", start.millis())

    return ee.ImageCollection(
        ee.List.sequence(0, weeks - 1).map(make_week)
    )

ndvi_weekly = weekly_composite("2022-11-01", 24, ndvi_ts)

ndvi_baseline = ndvi_weekly.mean().rename("NDVI_BASELINE")

ndvi_anomaly = ndvi_weekly.map(
    lambda img: img.subtract(ndvi_baseline)
                   .rename("NDVI_ANOMALY")
                   .set("system:time_start", img.get("system:time_start"))
)

stress_mask = ndvi_anomaly.map(
    lambda img: img.lt(-0.10).rename("STRESS")
)

stress_week = stress_mask.filterDate("2023-02-01", "2023-02-08").first()

task = ee.batch.Export.image.toDrive(
    image=stress_week,
    description="Wheat_Stress_Feb2023",
    folder="GEE_Wheat",
    fileNamePrefix="wheat_stress_feb",
    region=region,
    scale=10,
    maxPixels=1e13
)

task.start()

print(ndvi_weekly.size().getInfo())

stress_week = ee.Image(ndvi_anomaly.toList(24).get(14))

task = ee.batch.Export.image.toDrive(
    image=stress_week,
    description="Wheat_Stress_Week14",
    folder="GEE_Wheat",
    fileNamePrefix="wheat_stress_w14",
    region=region,
    scale=10,
    maxPixels=1e13
)

task.start()

"""# 📊 VISUALISING WHEAT HEALTH USING **MATPLOTLIB**"""

import rasterio
import numpy as np
import matplotlib.pyplot as plt

wheat_path   = "/content/drive/MyDrive/GEE_Wheat/wheat_map.tif"
baseline_path = "/content/drive/MyDrive/GEE_Wheat/ndvi_raw_test.tif"
stress_path   = "/content/drive/MyDrive/GEE_Wheat/wheat_stress_w14.tif"



# Wheat map
with rasterio.open(wheat_path) as src:
    wheat = src.read(1)
    wheat_nodata = src.nodata

# NDVI baseline
with rasterio.open(baseline_path) as src:
    baseline = src.read(1)
    baseline_nodata = src.nodata

# Stress map
with rasterio.open(stress_path) as src:
    stress = src.read(1)
    stress_nodata = src.nodata

# Replace nodata with NaN
if wheat_nodata is not None:
    wheat = np.where(wheat == wheat_nodata, np.nan, wheat)

if baseline_nodata is not None:
    baseline = np.where(baseline == baseline_nodata, np.nan, baseline)

if stress_nodata is not None:
    stress = np.where(stress == stress_nodata, np.nan, stress)

# Downsample factor (adjust if needed)
factor = 10

wheat_small = wheat[::factor, ::factor]

plt.figure(figsize=(6, 6))
plt.imshow(wheat_small, cmap="Greens", interpolation="nearest")
plt.title("Wheat Extent Map (Downsampled)")
plt.axis("off")
plt.show()

factor = 10   # increase to 15 or 20 if RAM is still tight

wheat_ds    = wheat[::factor, ::factor]
baseline_ds = baseline[::factor, ::factor]
stress_ds   = stress[::factor, ::factor]

plt.figure(figsize=(6, 6))
plt.imshow(
    baseline_ds,
    cmap="YlGn",
    vmin=0,
    vmax=0.8,
    interpolation="nearest"
)
plt.title("Seasonal NDVI Baseline (Wheat)")
plt.axis("off")
plt.colorbar(label="NDVI", fraction=0.046, pad=0.04)
plt.show()

plt.figure(figsize=(6, 6))
plt.imshow(
    stress_ds,
    cmap="Reds",
    interpolation="nearest"
)
plt.title("Early Wheat Stress (Feb 2023)")
plt.axis("off")
plt.colorbar(label="Stress (1 = stressed)", fraction=0.046, pad=0.04)
plt.show()

fig, axs = plt.subplots(1, 3, figsize=(18, 6))

axs[0].imshow(wheat_ds, cmap="Greens", interpolation="nearest")
axs[0].set_title("Wheat Extent")
axs[0].axis("off")

axs[1].imshow(
    baseline_ds,
    cmap="YlGn",
    vmin=0,
    vmax=0.8,
    interpolation="nearest"
)
axs[1].set_title("NDVI Baseline")
axs[1].axis("off")

axs[2].imshow(stress_ds, cmap="Reds", interpolation="nearest")
axs[2].set_title("Early Stress (Feb)")
axs[2].axis("off")

plt.tight_layout()
plt.show()

def mean_anomaly(img):
    mean_val = img.reduceRegion(
        reducer=ee.Reducer.mean(),
        geometry=region,
        scale=1000,        # coarse on purpose
        maxPixels=1e6
    ).get("NDVI_ANOMALY")

    return ee.Feature(None, {
        "date": img.date().format("YYYY-MM-dd"),
        "mean_anomaly": mean_val
    })

anomaly_fc = ee.FeatureCollection(ndvi_anomaly.map(mean_anomaly))

anomaly_data = anomaly_fc.getInfo()

dates = [f["properties"]["date"] for f in anomaly_data["features"]]
values = [f["properties"]["mean_anomaly"] for f in anomaly_data["features"]]

plt.figure(figsize=(9, 4))
plt.plot(dates, values, marker="o")
plt.axhline(-0.10, color="red", linestyle="--", label="Stress threshold")
plt.xticks(rotation=45)
plt.title("Weekly NDVI Anomaly Over Wheat")
plt.xlabel("Week")
plt.ylabel("NDVI Anomaly")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

s2 = (
    ee.ImageCollection("COPERNICUS/S2_SR")
    .filterBounds(region)
    .filterDate("2022-11-01", "2023-04-30")
)

def monthly_ndvi(start, end, name):
    return (
        s2.filterDate(start, end)
        .map(lambda img:
             img.normalizedDifference(["B8","B4"]))
        .median()
        .rename(name)
    )

ndvi_nov = monthly_ndvi("2022-11-01","2022-11-30","NOV")
ndvi_dec = monthly_ndvi("2022-12-01","2022-12-31","DEC")
ndvi_jan = monthly_ndvi("2023-01-01","2023-01-31","JAN")
ndvi_feb = monthly_ndvi("2023-02-01","2023-02-28","FEB")
ndvi_mar = monthly_ndvi("2023-03-01","2023-03-31","MAR")

ndvi_max = (
    ndvi_nov
    .max(ndvi_dec)
    .max(ndvi_jan)
    .max(ndvi_feb)
    .max(ndvi_mar)
).rename("MAX")

ndvi_min = ndvi_nov.min(ndvi_dec).rename("MIN")

amplitude = ndvi_max.subtract(ndvi_min).rename("AMP")

features = ee.Image.cat([
    ndvi_nov,
    ndvi_dec,
    ndvi_jan,
    ndvi_feb,
    ndvi_mar,
    ndvi_max,
    amplitude
])

train_region = ee.Geometry.Rectangle([
    75.0, 30.5,
    75.5, 31.0
])

wheat_mask = (
    ndvi_max.gt(0.45)
    .And(amplitude.gt(0.25))
).rename("WHEAT")



wheat_samples = wheat_mask.selfMask().stratifiedSample(
    numPoints=2000,
    classBand="WHEAT",
    region=train_region,
    scale=10,
    geometries=True
).map(lambda f: f.set("class",1))

non_wheat_mask = wheat_mask.Not()

non_wheat_samples = non_wheat_mask.selfMask().stratifiedSample(
    numPoints=2000,
    region=train_region,
    scale=10,
    geometries=True
).map(lambda f: f.set("class",0))

training_samples = wheat_samples.merge(non_wheat_samples)

training = features.sampleRegions(
    collection=training_samples,
    properties=["class"],
    scale=10,
    tileScale=8
)

classifier = ee.Classifier.smileRandomForest(
    numberOfTrees=150
).train(
    features=training,
    classProperty="class",
    inputProperties=features.bandNames()
)

wheat_rf = features.classify(classifier)

task = ee.batch.Export.image.toDrive(
    image=wheat_rf,
    description="RF_Wheat_Map",
    folder="GEE_Wheat",
    fileNamePrefix="rf_wheat",
    region=region,
    scale=10,
    maxPixels=1e13
)

task.start()



split = training.randomColumn()

train = split.filter("random < 0.7")
test  = split.filter("random >= 0.7")

model = ee.Classifier.smileRandomForest(150).train(
    train,
    "class",
    features.bandNames()
)

validated = test.classify(model)

matrix = validated.errorMatrix("class","classification")

print("Accuracy:", matrix.accuracy().getInfo())
print("Kappa:", matrix.kappa().getInfo())

import rasterio
import numpy as np
import matplotlib.pyplot as plt

rf_path = "/content/drive/MyDrive/GEE_Wheat/rf_wheat.tif"

with rasterio.open(rf_path) as src:
    wheat_rf = src.read(1, masked=True)

factor = 10   # increase if RAM tight

wheat_ds = wheat_rf[::factor, ::factor]

plt.figure(figsize=(7,7))

plt.imshow(
    wheat_ds,
    cmap="Greens",
    interpolation="nearest"
)

plt.title("Random Forest Wheat Classification")
plt.axis("off")

plt.colorbar(
    label="Class (1 = Wheat)",
    fraction=0.046,
    pad=0.04
)

plt.show()

plt.figure(figsize=(7,7))

plt.imshow(wheat_ds > 0.5, cmap="Greens")

plt.title("Detected Wheat Fields")
plt.axis("off")

plt.show()

ndvi_path = "/content/drive/MyDrive/GEE_Wheat/ndvi_raw_test.tif"

with rasterio.open(ndvi_path) as src:
    ndvi = src.read(1, masked=True)

ndvi_ds = ndvi[::factor, ::factor]

plt.figure(figsize=(7,7))

plt.imshow(
    ndvi_ds,
    cmap="YlGn",
    vmin=0,
    vmax=0.8
)

plt.title("Seasonal Peak NDVI")
plt.axis("off")
plt.colorbar(label="NDVI")

plt.show()

fig, axs = plt.subplots(1,2, figsize=(14,6))

axs[0].imshow(ndvi_ds, cmap="YlGn", vmin=0, vmax=0.8)
axs[0].set_title("NDVI Peak")
axs[0].axis("off")

axs[1].imshow(wheat_ds, cmap="Greens")
axs[1].set_title("RF Wheat Classification")
axs[1].axis("off")

plt.tight_layout()
plt.show()

pixel_area = 10 * 10   # m²

wheat_pixels = np.sum(wheat_rf > 0.5)

area_km2 = wheat_pixels * pixel_area / 1e6

print("Estimated Wheat Area (km²):", area_km2)

plt.figure(figsize=(5,5))

plt.bar(["Wheat Area"], [area_km2], color="green")

plt.ylabel("Area (km²)")
plt.title("Estimated Wheat Coverage")

plt.show()

plt.figure(figsize=(6,4))

plt.hist(
    wheat_rf.compressed(),
    bins=2
)

plt.title("Pixel Classification Distribution")
plt.xlabel("Class")
plt.ylabel("Pixel Count")

plt.show()

plt.figure(figsize=(7,7))
plt.imshow(wheat_ds, cmap="Greens")
plt.axis("off")

plt.savefig(
    "wheat_map.png",
    dpi=300,
    bbox_inches="tight"
)

with rasterio.open("/content/drive/MyDrive/GEE_Wheat/rf_wheat.tif") as src:
    wheat = src.read(1, masked=True)

with rasterio.open("/content/drive/MyDrive/GEE_Wheat/wheat_stress_w14.tif") as src:
    anomaly = src.read(1, masked=True)

factor = 10

wheat_ds = wheat[::factor, ::factor]
anom_ds  = anomaly[::factor, ::factor]

health = np.where(wheat_ds > 0.5, anom_ds, np.nan)

plt.figure(figsize=(7,7))

plt.imshow(
    health,
    cmap="RdYlGn",
    vmin=-0.2,
    vmax=0.2
)

plt.title("Wheat Health Condition")
plt.axis("off")
plt.colorbar(label="NDVI Anomaly")

plt.show()

stress = health < -0.10

plt.figure(figsize=(7,7))
plt.imshow(stress, cmap="Reds")

plt.title("Early Wheat Stress Detection")
plt.axis("off")
plt.show()

plt.figure(figsize=(7,7))

plt.imshow(
    health,
    cmap="coolwarm",
    vmin=-0.25,
    vmax=0.25
)

plt.title("Stress Intensity Map")
plt.axis("off")
plt.colorbar(label="Stress Severity")

plt.show()

total_wheat = np.sum(wheat > 0.5)
stressed = np.sum((anomaly < -0.10) & (wheat > 0.5))

percent = (stressed / total_wheat) * 100

print("Percent Wheat Under Stress:", percent)

fig, axs = plt.subplots(1,3, figsize=(18,6))

axs[0].imshow(wheat_ds, cmap="Greens")
axs[0].set_title("Wheat Extent")
axs[0].axis("off")

axs[1].imshow(health, cmap="RdYlGn",
              vmin=-0.2, vmax=0.2)
axs[1].set_title("Crop Health")
axs[1].axis("off")

axs[2].imshow(stress, cmap="Reds")
axs[2].set_title("Early Stress Zones")
axs[2].axis("off")

plt.tight_layout()
plt.show()

with rasterio.open("rf_wheat.tif") as src:
    wheat = src.read(1, masked=True)